name: Fetch Songs

on:
  push:
    branches:
      - main

jobs:
  fetch_songs:
    runs-on: windows-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Disable line-ending conversion
        run: |
          git config --global core.autocrlf false
        
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Execute fetch_songs.py
        run: python fetch_songs.py

      - name: Commit changes
        run: |
          git config --global user.name ${NAME}
          git config --global user.email ${EMAIL}
          git add .
          git commit -m "Update soundtrack info" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:${{ github.ref }}
        env:
          NAME: ${GITHUB_ACTOR}
          EMAIL: ${GITHUB_ACTOR}@users.noreply.github.com